### ISSUE TITLE
thừa

### ISSUE THREAD

**Issue by SocolaDaiCa** [minhnt95/firework-chrome-extension#1]
đoạn trong file firework.js có vẻ hơi thừa
```javascript
chrome.browserAction.onClicked.addListener(function (tab) {
	chrome.tabs.create({url: "dashboard.html"});
});
```
mình thấy có lẽ là đoạn
```json
"chrome_url_overrides": {
        "newtab": "dashboard.html"
    },
```
trong file manifest.json đã đủ để thực hiện công việc thay đổi tab mặc định

**Comment by m-inh** [comment]
@SocolaDaiCa cậu thử xóa dòng đó rồi chạy thử chưa?

**Comment by SocolaDaiCa** [comment]
mình thử rồi, k có đoạn js nó vẫn chạy ầm ầm

**Comment by m-inh** [comment]
vậy thì t sẽ bỏ nó đi. lâu rồi ko động nên t cũng không nhớ lắm :d
